install.packages("caret")
getwd()
setwd( "C:/Users/a0105/OneDrive/문서")
bumpus<-read.csv("Bumpus.csv")
class(bumpus)
attach(bumpus)
str(bumpus)
head(bumpus)
summary(bumpus)
par(mfrow=c(1,1))
plot(alar~length, xlab="Length",ylab = "Alar",main="Hermon Bumpus")
plot(alar~length, xlab="Length",ylab = "Alar",main="Hermon Bumpus",pch=15)
plot(alar~length, xlab="Length",ylab = "Alar",main="Hermon Bumpus"pch=22,bg="red")     
plot(alar~length, xlab="Length",ylab = "Alar",main="Hermon Bumpus",pch=8,bg="green")
plot(alar~length,,col=survive, pch=c(0,15),bg="red",xlab="Length",ylab = "Alar",main="Hermon Bumpus")
iris<-read.csv("iris.csv")
head(iris)
str(iris)
str(iris3)
head(iris3)