bumpus<-read.csv("C:/R/bumpus.csv",encoding="UFT-8")
head(bumpus)
class(bumpus)
str(bumpus)
bumpus<-subset(bumpus,select = c("X1","X2","X3","X4","X5"))
class(bumpus)
head(bumpus)
summary(bumpus)
CM<-round(cov(scale(bumpus)),3)
CM
round(cor(scale(bumpus)),3)
class(CM)
eigen(CM)
round(eigen(CM)$values,3)
round(eigen(CM)$vectors,3)
-1*round(eigen(CM)$vectors,2)
pca<-prcomp(bumpus,scale =T)
summary(pca)
screeplot(pca,type = "l",pch=19,lwd=3,col="black",main = "screen plot")
biplot(pca,cex=c(0.5,0.75),main="biplot")