str(iris)
levels(iris$Species)
a <- subset(iris, Species == "setosa" | species == "versicolor")
str(a)
a
b <- glm(Species- sepal.Length, data = a, family ="binomial")
summary(b)
fitted(b)[c(1:5, 96:100)]
x = seq(min(a$Sepal.Length), max(iris$Sepal.Length), 0.1)
y = 1/(1+(1/exp(-27.831+5.140*x)))
plot(y-x, type="1", xlab = "Sepal.Length", ylab = "versicolor")
y = 1+1/(1+(1/exp(-27.831+5.140*x)))
plot(y-x, type="1", xlab = "Sepal.Length", ylab = "versicolor")
aggerate(Sepal.Length-Speices, a, mean)
aggerate(Sepal.Length-Speices, iris, mean)
c <- glm(Species- sepal.Length+Sepal.width+petal.Length+petal.width, data = a, family ="binomial")
summary(c)
reduced <-step(c, direction = 'backward')
summary(reduced)
