data("iris")
library(el071)
f_0.1<-svm(Species~., data=iris, type="c-classfication", kernel="radial", cost=10, gamma=0.1)
summary(f_0.1)
p_0.1<-predict(f_0.1, iris, decision.values = TRUE)
summary(p_0.1)
acc_0.1 <-table(p_0.1, iris$Species)
classAgreement(acc_0.1)
plot(f_0.1, iris, Petal.Width~PEtal.Length, slice=list(Sepal.Width=3, Sepal.Length=4))
