data("Titanic")
class(Titanic)
Titanic
library(earth)
data("etitanic")
class(etitanic)
attach(etitanic)
str(etitanic)
head(etitanic)
head(model.matrix(survived~.,data = etitanic))
fit<-model.matrix(survived~.,data = etitanic)
head(fit)
dummy<-dummyVars(survived~.,data = etitanic)
pfit<-predict(dummy,newdata=etitanic)
head(pfit)
head(etitanic)
class(airquality)
head(airquality)
summary(airquality)
imp<-preprocess(airquality,method=c("knnImpute"))
dim(airquality)
pa<-predict(imp,airquality)
dim(pa)
summary(pa)
omitted<-na.omit(airquality)
dim(omitted)
summary(omitted)
airquality$Ozone<-ifelse(is.na(airquality$Ozone),mean(airquality$Ozone,na.rm = T),airquality$Ozone)
ifelse(is.na(airquality$Solar.R),mean(airquality$Solar.R,na.rm = T),airquality$Solar.R)
summary(airquality)
dim(airquality)