data(trees)
summary(trees)
head(trees)
dim(trees)
str(trees)
fit1<-lm(formula = trees$Height~trees$Girth,data=trees)
summary(fit1)
cor(trees)
fit2<-lm(trees$Height~trees$Volume,data = trees)
summary(fit2)
fit<-lm(trees$Height~trees$Girth+trees$Volume,data = trees)
summary(fit)
library(olsrr)
full_model<-fit
ols_mallows_cp(fit,full_model)
ols_mallows_cp(fit2,full_model)